#!/usr/bin/env bash

set -euo pipefail

# Detect absolute path to the directory where "lib.include.sh" resides.
export SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"

# Ensure that all scripts change their working dir to the root of the project.
cd -- "${SCRIPT_DIR}"

# User-configurable environment variables.
# IMPORTANT: Do not edit this file for local preferences; pass these variables via the environment.
export OT_UV_VERSION="${OT_UV_VERSION:-0.9.17}"
export OT_PYTHON_VERSION="${OT_PYTHON_VERSION:-3.13}"
export OT_LAZY_UPDATES="${OT_LAZY_UPDATES:-false}"
export OT_CUDA_LOWMEM_MODE="${OT_CUDA_LOWMEM_MODE:-false}"
export OT_PLATFORM_REQUIREMENTS="${OT_PLATFORM_REQUIREMENTS:-detect}"
export OT_SCRIPT_DEBUG="${OT_SCRIPT_DEBUG:-false}"

# Internal environment variables.
export OT_PYTHON_VERSION_MINIMUM="3.10"
export OT_PYTHON_VERSION_TOO_HIGH="3.14"
export OT_MUST_INSTALL_REQUIREMENTS="false"
export OT_UPDATE_METADATA_FILE="${SCRIPT_DIR}/update.var"
export OT_HOST_OS="$(uname -s)"
export OT_UV_DIR="${SCRIPT_DIR}/.uv/bin"
export OT_UV_BIN="${OT_UV_DIR}/uv"
export UV_CACHE_DIR="${UV_CACHE_DIR:-${SCRIPT_DIR}/.uv/cache}"
export UV_PYTHON_INSTALL_DIR="${SCRIPT_DIR}/.uv/python"
export UV_TOOL_DIR="${SCRIPT_DIR}/.uv/tools"
export UV_TOOL_BIN_DIR="${SCRIPT_DIR}/.uv/tool-bin"
export UV_PYTHON_INSTALL_BIN=0
export UV_PYTHON_PREFERENCE="only-managed"
export UV_PYTHON_DOWNLOADS="manual"
export PYTHONPATH="${SCRIPT_DIR}${PYTHONPATH:+:${PYTHONPATH}}"

# Force PyTorch to use fallbacks on Mac systems.
if [[ "${OT_HOST_OS}" == "Darwin" ]]; then
    export PYTORCH_ENABLE_MPS_FALLBACK="1"
fi

# Change PyTorch memory allocation to reduce CUDA out-of-memory situations.
if [[ "${OT_CUDA_LOWMEM_MODE}" == "true" ]]; then
    export PYTORCH_CUDA_ALLOC_CONF="garbage_collection_threshold:0.6,max_split_size_mb:128"
fi

# Utility functions.
function escape_shell_command {
    printf " %q" "$@" | sed 's/^ //'
}

function print {
    printf "[OneTrainer] %b\n" "$*"
}

function print_warning {
    printf "[OneTrainer] Warning: %b\n" "$*" >&2
}

function print_error {
    printf "[OneTrainer] Error: %b\n" "$*" >&2
}

function print_debug {
    if [[ "${OT_SCRIPT_DEBUG}" == "true" ]]; then
        print "Debug: $*"
    fi
}

function print_command {
    printf "[OneTrainer] + %s\n" "$(escape_shell_command "$@")"
}

function run_cmd {
    print_command "$@"
    "$@"
}

function normalize_bool {
    if [[ -z "$1" ]]; then
        echo "false"
        return 0
    fi

    local value
    value="$(printf '%s' "$1" | tr '[:upper:]' '[:lower:]')"
    case "${value}" in
        1|true|yes|on) echo "true" ;;
        0|false|no|off) echo "false" ;;
        *)
            print_error "Invalid boolean value '$1'. Expected true/false, yes/no, on/off, or 1/0."
            exit 1
            ;;
    esac
}

export OT_LAZY_UPDATES="$(normalize_bool "${OT_LAZY_UPDATES}")"
export OT_CUDA_LOWMEM_MODE="$(normalize_bool "${OT_CUDA_LOWMEM_MODE}")"
export OT_SCRIPT_DEBUG="$(normalize_bool "${OT_SCRIPT_DEBUG}")"

function reject_removed_env_vars {
    local removed_vars=(OT_CONDA_CMD OT_CONDA_ENV OT_PYTHON_CMD OT_PYTHON_VENV OT_PREFER_VENV OT_CONDA_USE_PYTHON_VERSION)
    local name
    for name in "${removed_vars[@]}"; do
        if [[ -n "${!name+x}" ]]; then
            print_error "Environment variable '${name}' is no longer supported. OneTrainer now uses repo-local uv-managed Python."
            exit 1
        fi
    done
}

reject_removed_env_vars
export OT_LOCAL_PYTHON_ENV_PATH="${SCRIPT_DIR}/.venv"
export OT_PYTHON_BIN="${OT_LOCAL_PYTHON_ENV_PATH}/bin/python"

# Retrieves the most recent Git commit's hash.
function get_current_git_hash {
    git rev-parse HEAD
}

# Writes update-check metadata to disk.
function save_update_metadata {
    get_current_git_hash >"${OT_UPDATE_METADATA_FILE}"
}

# Checks whether the current Git state matches the last-seen metadata state.
function is_update_metadata_changed {
    if [[ -f "${OT_UPDATE_METADATA_FILE}" ]]; then
        local saved_hash="$(<"${OT_UPDATE_METADATA_FILE}")"
        local current_hash="$(get_current_git_hash)"
        print_debug "Saved Metadata Hash=\"${saved_hash}\", Current Hash=\"${current_hash}\""
        if [[ "${saved_hash}" == "${current_hash}" ]]; then
            return 1
        fi
    fi

    return 0
}

function can_exec {
    if [[ -z "$1" ]]; then
        print_error "can_exec requires 1 argument."
        return 1
    fi

    if local full_path="$(command -v "$1" 2>/dev/null)"; then
        if [[ -n "${full_path}" && -x "${full_path}" ]]; then
            return 0
        fi
    fi

    return 1
}

function bootstrap_uv {
    if [[ -x "${OT_UV_BIN}" ]]; then
        return 0
    fi

    if ! can_exec curl; then
        print_error "Missing 'curl' on PATH; required to download uv."
        exit 1
    fi

    mkdir -p "${OT_UV_DIR}" "${UV_CACHE_DIR}" "${UV_PYTHON_INSTALL_DIR}"
    print "Installing uv ${OT_UV_VERSION} into \"${OT_UV_DIR}\"..."
    curl -LsSf "https://astral.sh/uv/${OT_UV_VERSION}/install.sh" | \
        env UV_NO_MODIFY_PATH=1 UV_UNMANAGED_INSTALL="${OT_UV_DIR}" sh

    if [[ ! -x "${OT_UV_BIN}" ]]; then
        print_error "uv install completed but \"${OT_UV_BIN}\" is missing or not executable."
        exit 1
    fi
}

function install_managed_python {
    print "Installing managed Python ${OT_PYTHON_VERSION}..."
    run_cmd "${OT_UV_BIN}" python install "${OT_PYTHON_VERSION}"
}

function ensure_python_venv_exists {
    if [[ -e "${OT_LOCAL_PYTHON_ENV_PATH}" && ! -d "${OT_LOCAL_PYTHON_ENV_PATH}" ]]; then
        print_error "Expected Python environment path to be a directory: \"${OT_LOCAL_PYTHON_ENV_PATH}\"."
        exit 1
    fi

    if [[ -x "${OT_PYTHON_BIN}" ]]; then
        return 0
    fi

    if [[ -d "${OT_LOCAL_PYTHON_ENV_PATH}" ]]; then
        print_error "Python environment exists but is incomplete; missing executable: \"${OT_PYTHON_BIN}\". Delete the directory and rerun install.sh."
        exit 1
    fi

    print "Creating uv virtual environment in \"${OT_LOCAL_PYTHON_ENV_PATH}\"..."
    run_cmd "${OT_UV_BIN}" venv --python "${OT_PYTHON_VERSION}" "${OT_LOCAL_PYTHON_ENV_PATH}"
    export OT_MUST_INSTALL_REQUIREMENTS="true"
}

function run_python_in_active_env {
    run_cmd "${OT_UV_BIN}" run --python "${OT_PYTHON_BIN}" --no-sync python "$@"
}

function run_uv_pip_install_in_active_env {
    run_cmd "${OT_UV_BIN}" pip install --python "${OT_PYTHON_BIN}" "$@"
}

# Determines which requirements.txt file we need to install.
function get_platform_requirements_path {
    local platform_reqs="${OT_PLATFORM_REQUIREMENTS}"
    if [[ "${platform_reqs}" == "detect" ]]; then
        if [[ -e "/dev/nvidia0" ]] || can_exec nvidia-smi || can_exec "/usr/lib/wsl/lib/nvidia-smi"; then
            platform_reqs="requirements-cuda.txt"
        elif [[ -e "/dev/kfd" ]]; then
            platform_reqs="requirements-rocm.txt"
        else
            platform_reqs="requirements-default.txt"
        fi
    fi

    if [[ -z "${platform_reqs}" || ! -f "${platform_reqs}" ]]; then
        print_error "Requirements file \"${platform_reqs}\" does not exist."
        return 1
    fi

    echo "${platform_reqs}"
}

# Installs the Global and Platform requirements into the active environment.
function install_requirements_in_active_env {
    print "Installing requirements in uv-managed environment..."
    run_uv_pip_install_in_active_env --upgrade pip setuptools==81.0.0

    local platform_requirements_path
    platform_requirements_path="$(get_platform_requirements_path)"
    local uv_pip_install_args=(--upgrade)
    if [[ "${platform_requirements_path}" == "requirements-default.txt" ]]; then
        uv_pip_install_args+=(--torch-backend cpu)
    fi
    run_uv_pip_install_in_active_env "${uv_pip_install_args[@]}" -r requirements-global.txt -r "${platform_requirements_path}"
    export OT_MUST_INSTALL_REQUIREMENTS="false"

    if [[ "${OT_LAZY_UPDATES}" == "true" ]]; then
        print_debug "Saving current update-check metadata to disk..."
        save_update_metadata
    elif [[ -f "${OT_UPDATE_METADATA_FILE}" ]]; then
        print_debug "Deleting outdated update-check metadata from disk..."
        rm -f "${OT_UPDATE_METADATA_FILE}"
    fi
}

function install_requirements_in_active_env_if_necessary {
    if [[ "${OT_MUST_INSTALL_REQUIREMENTS}" != "false" ]]; then
        install_requirements_in_active_env
    fi
}

function show_runtime_solutions {
    print "Solution: Run ./install.sh again. OneTrainer now uses repo-local uv-managed Python in .venv with managed Python files under .uv/python. Delete .venv and rerun ./install.sh if the environment was created with an incompatible Python version."
}

function exit_if_active_env_wrong_python_version {
    if ! run_python_in_active_env "scripts/util/version_check.py" "${OT_PYTHON_VERSION_MINIMUM}" "${OT_PYTHON_VERSION_TOO_HIGH}"; then
        show_runtime_solutions
        exit 1
    fi
}

# Performs the most important startup sanity checks and environment preparation.
function prepare_runtime_environment {
    bootstrap_uv
    install_managed_python
    ensure_python_venv_exists
    exit_if_active_env_wrong_python_version

    local force_update="false"
    if [[ "${1:-}" == "upgrade" ]]; then
        if [[ "${OT_LAZY_UPDATES}" == "false" ]] || is_update_metadata_changed; then
            force_update="true"
        fi
    fi

    if [[ "${force_update}" == "true" ]]; then
        print_debug "Triggering a forced update of the environment's dependencies..."
        install_requirements_in_active_env
    else
        install_requirements_in_active_env_if_necessary
    fi
}
