import re
import argparse
from pathlib import Path

def parse_import_times(log_filepath: Path) -> dict[str, int]:
    """
    Parses the output of 'python -X importtime' to extract cumulative import times.
    (Função inalterada - continua igual à versão anterior)
    """
    import_times = {}
    regex = re.compile(r"^import time:\s*\d+\s*\|\s*(\d+)\s*\|\s*(.*?)(?:\s*#.*)?$", re.IGNORECASE | re.MULTILINE)

    print(f"Processing log file: {log_filepath}")
    line_count = 0
    parsed_count = 0
    try:
        with open(log_filepath, 'r', encoding='utf-8') as f:
            for line in f:
                line_count += 1
                match = regex.match(line.strip())
                if match:
                    try:
                        cumulative_time_us = int(match.group(1))
                        module_name = match.group(2).strip()
                        import_times[module_name] = cumulative_time_us
                        parsed_count += 1
                    except ValueError:
                        print(f"  [WARN] Skipping line {line_count}: Could not parse numbers in: {line.strip()}")
                    except IndexError:
                         print(f"  [WARN] Skipping line {line_count}: Could not parse structure in: {line.strip()}")

    except FileNotFoundError:
        print(f"[ERROR] Log file not found: {log_filepath}")
        return {}
    except Exception as e:
        print(f"[ERROR] Failed to read or parse log file: {e}")
        return {}

    print(f"Processed {line_count} lines, parsed {parsed_count} import time entries.")
    return import_times

# START: Modificação para salvar em arquivo
def display_sorted_times(import_times: dict[str, int], output_filepath: Path | None = None):
    """
    Sorts and displays the import times from slowest to fastest,
    either printing to console or saving to a file.

    Args:
        import_times: Dictionary mapping module names to cumulative import times (us).
        output_filepath: Optional path to save the output. If None, prints to console.
    """
    if not import_times:
        print("No import time data to process.")
        return

    sorted_times = sorted(import_times.items(), key=lambda item: item[1], reverse=True)

    # Preparar as linhas de cabeçalho
    header_lines = [
        "--- Import Times (Cumulative, Slowest First) ---",
        f"{'Module':<60} | {'Time (ms)':>12}",
        "-" * 75
    ]
    # Preparar as linhas de dados (filtrando por tempo > 1ms, por exemplo)
    data_lines = []
    threshold_ms = 1.0
    for module, time_us in sorted_times:
        time_ms = time_us / 1000.0
        if time_ms >= threshold_ms:
            data_lines.append(f"{module:<60} | {time_ms:>12.3f}")

    # Preparar as linhas de rodapé
    footer_lines = [
        "-" * 75,
        f"Total unique modules recorded (above {threshold_ms}ms threshold): {len(data_lines)}",
        f"Total unique modules recorded (overall): {len(sorted_times)}"
    ]

    # Combinar todas as linhas
    output_content = "\n".join(header_lines + data_lines + footer_lines)

    if output_filepath:
        try:
            with open(output_filepath, 'w', encoding='utf-8') as f:
                f.write(output_content + "\n") # Adiciona uma newline no final do arquivo
            print(f"Successfully saved sorted import times to: {output_filepath}")
        except Exception as e:
            print(f"[ERROR] Failed to write output file '{output_filepath}': {e}")
            # Se falhar ao escrever, imprime no console como fallback
            print("\n--- Outputting to console instead: ---")
            print(output_content)
    else:
        # Imprimir no console se nenhum arquivo de saída foi especificado
        print("\n" + output_content)

# END: Modificação para salvar em arquivo

if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Parse and sort Python '-X importtime' log output."
    )
    parser.add_argument(
        "logfile",
        type=Path,
        help="Path to the log file generated by 'python -X importtime'.",
    )
    # START: Adicionar argumento de saída
    parser.add_argument(
        "-o",
        "--output",
        type=Path,
        default=None, # Nenhum arquivo por padrão
        help="Optional path to save the sorted output list."
    )
    # END: Adicionar argumento de saída
    args = parser.parse_args()

    times = parse_import_times(args.logfile)
    # START: Passar argumento de saída para a função
    display_sorted_times(times, args.output)
    # END: Passar argumento de saída para a função